spring.application.name=gateway
# secret key
JWT_SECRET=DLOKMFOPSJFOPSJFOPSJFPOJSOPFJOPSJFOPSJFOPfdlpokmspssfdpk
# redis
spring.redis.host=redis
spring.redis.port=6379


logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.reactor.netty=DEBUG