services:
  orders:
    image: prithvi069/nexora-orders:latest
    pull_policy: always
    ports:
      - "8084:8084"
    networks:
      - nexora-network

  products:
    image: prithvi069/nexora-products:latest
    pull_policy: always
    ports:
      - "8082:8082"
    environment:
      - AWS_ACCESS_KEY={access_key}
      - AWS_SECRET_KEY={secret_key}
    networks:
      - nexora-network

  payments:
    image: prithvi069/nexora-payments:latest
    pull_policy: always
    ports:
      - "8085:8085"
    networks:
      - nexora-network

  notifications:
    image: prithvi069/nexora-notifications:latest
    pull_policy: always
    ports:
      - "8086:8086"
    networks:
      - nexora-network

networks:
  nexora-network:
    external: true
    name: nexora-network
