services:
  gateway:
    image: prithvi069/nexora-gateway:latest
    pull_policy: always
    ports:
      - "8080:8080"
    networks:
      - nexora-network

networks:
  nexora-network:
    external: true
    name: nexora-network
