services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nexora
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nexora-network

networks:
  nexora-network:
    external: true
    name: nexora-network

volumes:
  mysql-data:
