pipeline {
    agent any

    tools {
        maven 'mvn'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Prithvi333/Nexora.git'
            }
        }

        stage('Check Auth Changes') {
            steps {
                script {
                    def changedFiles = sh(
                        script: 'git diff --name-only HEAD~1 HEAD',
                        returnStdout: true
                    ).trim()

                    if (!changedFiles.contains('services/auth/')) {
                        currentBuild.result = 'NOT_BUILT'
                        error('No changes found in services/auth')
                    }
                }
            }
        }

        stage('Build JAR') {
            steps {
                dir('services/auth') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('services/auth') {
                    sh 'docker build -t prithvi069/nexora-auth .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'docker-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push prithvi069/nexora-auth
                        docker logout
                    '''
                }
            }
        }
    }
}